spring:
  application:
    name: api
  datasource:
    url: jdbc:h2:file:~/test;USER=sa;PASSWORD=password;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: password
  jpa:
    properties:
      hibernate.hbm2ddl.auto: create-drop
      general-ddl: true
