spring:
  application:
    name: api
db1:
  jdbc-url: jdbc:h2:file:~/test;USER=sa;PASSWORD=password;DB_CLOSE_ON_EXIT=FALSE;
  username: sa
  password: password
db2:
  jdbc-url: jdbc:h2:file:~/test2;USER=sa;PASSWORD=password;DB_CLOSE_ON_EXIT=FALSE;
  username: sa
  password: password
